name: dockrsync

services:
  rsync:
    build: .
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Berlin
      SCHEDULE: "0 3 * * *"
      SOURCES: |
        docker-volumes=/source/docker-volumes
        appdata=/source/appdata
      BACKUP_DIR: /backup
      DELETE_EXTRANEOUS: "true"
      KUMA_BASE: ""
      KUMA_TOKEN: ""
    volumes:
      - /var/lib/docker/volumes:/source/docker-volumes:ro
      - /opt/appdata:/source/appdata:ro
      - /mnt/backup:/backup
