name: dockstorebackup

services:
  storebackup:
    image: ghcr.io/wikibear/dockstorebackup:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Berlin
      SCHEDULE: "0 3 * * *"
      SOURCES: |
        docker-volumes=/source/docker-volumes
        appdata=/source/appdata
      BACKUP_DIR: /backup
      KEEP_DAYS: "7"
      KEEP_WEEKS: "4"
      KEEP_MONTHS: "12"
      KUMA_URL: ""
      KUMA_TOKEN: ""
    volumes:
      - /var/lib/docker/volumes:/source/docker-volumes:ro
      - /opt/appdata:/source/appdata:ro
      - /mnt/backup:/backup
